# Site settings
title: Sam's blog
email: shaoming.mei#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  go big or go home.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "smmei.github.com" # the base hostname & protocol for your site
twitter_username:
github_username:  smmei

# Build settings
markdown: redcarpet
highlighter: pygments
